# Generated by Django 6.0.7 on 2026-09-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ingrediente', 'verbose_name_plural': 'ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['display_order', 'price'], 'verbose_name': 'opção de produto', 'verbose_name_plural': 'opções de produto'},
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PIZZA', 'Pizza'), ('PASTEL', 'Pastel'), ('DRINK', 'Bebida')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
