# Generated by Django 6.0.2 on 2026-06-09 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, choices=[('GOALKEEPER', 'Goleiro'), ('DEFENDER', 'Defensor'), ('MIDFIELDER', 'Meio-campo'), ('FORWARD', 'Atacante')], max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['name'],
            },
        ),
    ]
