# Generated by Django 6.0.2 on 2026-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('modality', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('SOCIETY', 'Society'), ('FUTSAL', 'Futsal')], max_length=20)),
                ('format', models.CharField(choices=[('LEAGUE', 'Pontos Corridos'), ('GROUPS', 'Fase de Grupos'), ('KNOCKOUT', 'Mata-Mata')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='championships', to='teams.team')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'ordering': ['-created_at'],
            },
        ),
    ]
