# Generated by Django 6.0.2 on 2026-06-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_standing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standing',
            old_name='gols_against',
            new_name='goals_against',
        ),
        migrations.RenameField(
            model_name='standing',
            old_name='gols_for',
            new_name='goals_for',
        ),
    ]
