# Generated by Django 6.0.2 on 2026-06-09 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('shield', models.ImageField(blank=True, null=True, upload_to='team_shields/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['name'],
            },
        ),
    ]
